### ISSUE TITLE
B1.3 Drafted version of factsheet is uploaded 

### ISSUE THREAD

**Issue by JasonKaWaiMa** [anuships/SHIPS-Group#2]
Factsheet commit e5378d101bf1aae8410e33f59b2aef52a2872939

**Comment by JasonKaWaiMa** [comment]
Testing

**Comment by jlyds** [comment]
good luck

**Comment by JasonKaWaiMa** [comment]
The layout of factsheet is revised commit 05291f461e43411f9d49b31d4ff652fb881457f1

**Comment by JasonKaWaiMa** [comment]
Font size adjusted
commit 4e5f5d4d869f64bc15919dca753f1df1df10418a
