### ISSUE TITLE
Export android app to .apk for Buisness students.

### ISSUE THREAD

**Issue by u5564556** [anuships/SHIPS-Group#21]
Export the android application into a standalone .apk, to allow the app to be downloaded/installed by others.

**Comment by jlyds** [comment]
Uploaded to Google Drive (or should be updoaded to other platform?)
https://drive.google.com/drive/u/0/folders/0B-sNkIr15AkJSmZLREs1TEo2X2M

Path in GD: SHIPS-ANU/Platform Resources/Android APP APK
