### ISSUE TITLE
Feedback summary for audit 1

### ISSUE THREAD

**Issue by JasonKaWaiMa** [anuships/SHIPS-Group#28]
Feedback summary drafted by Jason Ma
[Feedback audit 1](https://drive.google.com/open?id=0B11EO3-EiomARUNVTE5ES2pUYjg)

**Comment by u5964628** [comment]
I've inserted a minor comment in the last page of the slides.

**Comment by JasonKaWaiMa** [comment]
Revised according Yiu Kei's comment
