### ISSUE TITLE
User testing checklist

### ISSUE THREAD

**Issue by lalitpras** [anuships/SHIPS-Group#44]
Write a checklist to guide user feedback when testing our application.

Questions are to target the usability and usefulness of the application, as well as aesthetics. NOT technical/functional questions that can be checked ourselves.

To be finalised after peer review on Friday 22nd September

**Comment by lalitpras** [comment]
Added some general and EMDR-specific questions. It would be best if each team member can add the questions that they think are most suitable (obtaining best feedback for further development).

**Comment by lalitpras** [comment]
Split into two sections: guided navigation through the features with basic feedback at each stage (what do you like, what confuses you and what annoys you), followed by a user checklist to fill out (minimal set of questions for each feature regarding usability and aesthetics).

**Comment by lalitpras** [comment]
I will write the navigation section using Yiukei's helpful example. Others can just write the three most important questions for each of their features in the checklist section

**Comment by lalitpras** [comment]
Plan for collecting user testing can be found here:
https://docs.google.com/document/d/1m60Y6rgnVvFeHKSOipU99D_ojH98SxRnxh3iMYSaKKI/edit
Please review and comment in the discussion when done

**Comment by JasonKaWaiMa** [comment]
Hi, Lalit, Yiu Kei and me added some comments in the file (you can find them in the comments blocks of in the file), you may have a look, thanks.
