### ISSUE TITLE
4th Team Meeting Minutes and 5th Team Meeting Agenda

### ISSUE THREAD

**Issue by u5964628** [anuships/SHIPS-Group#49]
4th team meeting minutes (https://drive.google.com/file/d/0BxEiU-mPw7eVRU00R0VqM2N3MUk/view) and 5th team meeting agenda (https://drive.google.com/file/d/0BxEiU-mPw7eVRmd6R21SaVdHRmc/view) for your comments.

**Comment by JasonKaWaiMa** [comment]
Some issues are added into 5th team meeting agenda
