### ISSUE TITLE
Constraints and risk management

### ISSUE THREAD

**Issue by JasonKaWaiMa** [anuships/SHIPS-Group#50]
The plans for constraints and risk management are drafted based on discussions in team, client and tutor meetings. Please find the plans in the following documents
[Constraints and risk management](https://drive.google.com/open?id=1jYxinVKbMbVhO9I6C6ZykTiq4UfgUtkoDw9q4oBP4RI)

**Comment by u5964628** [comment]
I've inserted a few edits in the file.
