### ISSUE TITLE
Project audit 2 presentation

### ISSUE THREAD

**Issue by JasonKaWaiMa** [anuships/SHIPS-Group#61]
Planning:
Nicole: Documentation and decision making 
Lalit: Introduction and User story map and values
Jason: Website and Android development and other progress
Jayden, Yiu Kei and Kevin: Q&A

**Comment by jlyds** [comment]
Same document in Google Drive
https://docs.google.com/document/d/1rkyNuC7BezM-UiMlCj79zt7tZj44-bckNFOVIE1dYMo/edit?usp=sharing

**Comment by JasonKaWaiMa** [comment]
PPT for Website and Android development and other progress is drafted
