### ISSUE TITLE
Research on technical information of flying for factsheet

### ISSUE THREAD

**Issue by csqyin** [anuships/SHIPS-Group#83]
To get more info on technical information flying that will be included in the factsheet

**Comment by csqyin** [comment]
Still ongoing with the research. Saved in Factsheet file. Named Technical Research [https://drive.google.com/drive/folders/0Bz9352WjbyDlYTFQczFQMWMwb2c](url)

**Comment by JasonKaWaiMa** [comment]
It seems I cannot open the link (404 error), not sure if the file is created or uploaded.

**Comment by csqyin** [comment]
Yee just fixed it. sorry about it.

**Comment by csqyin** [comment]
Have finished the research. Will create a factsheet WordPress Page with research content on it.
