### ISSUE TITLE
1. Create PHP Code on Web Server to allow register/login via http post.

### ISSUE THREAD

**Issue by u5564556** [anuships/SHIPS-Group#9]

**Comment by jlyds** [comment]
this is already developing refer to #4

**Comment by jlyds** [comment]
implemeted function on a local server, waiting for next step to test running on Amazon server side

**Comment by u5564556** [comment]
https://github.com/anuships/SHIPS-Group/commit/8414117ef583447884f1354b92ca7af9437758d1
